services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:sikapos123@db:5432/sikapos_cloud
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sikapos123
      - POSTGRES_DB=sikapos_cloud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Host port 5433 to avoid conflict with local PG
    restart: always

volumes:
  postgres_data:
